##### RHEL
#kstest_boot_iso_url: "http://download.eng.brq.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.3.0/compose/BaseOS/x86_64/os/images/boot.iso"
kstest_boot_iso_url: "http://10.43.136.2/trees/rhel-8-scratch/bug1844578_boot.iso"
kstest_url: "--url=http://download.eng.brq.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.3.0/compose/BaseOS/x86_64/os/"
kstest_repos:
        - "repo --name=appstream --baseurl=http://download.eng.brq.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.3.0/compose/AppStream/x86_64/os/"
kstest_ftp_url: "ftp://download.devel.redhat.com/mnt/redhat/nightly/latest-RHEL-8/compose/BaseOS/x86_64/os/"
kstest_unified_url: "--url=http://download.eng.brq.redhat.com/rhel-8/rel-eng/RHEL-8/latest-RHEL-8/compose/unified/x86_64/"
#kstest_updates_img: "https://rvykydal.fedorapeople.org/updates.race-hunt.img"
#kstest_updates_img: "http://10.43.136.2/ks/rv/updates.race-hunt.img"
kstest_test_jobs: 6
kstest_remote_results_keep_local: "no"
kstest_skip_test_types: "fedora-only"
kstest_platform: rhel8
#kstest_tests_to_run: "network-autoconnections-httpks"
#kstest_tests_to_run: "bindtomac-network-device-default-httpks firewall-disable-with-options module-enable-one-module-multiple-times network-device-default-httpks network-device-default-ksdevice-pre user-locked-root-locked-admin"
kstest_git_repo: https://github.com/rvykydal/kickstart-tests.git
#kstest_git_version: update-network-autoconnections-test-for-NM-change
kstest_git_version: hunt-for-race-get-variant
