---

- name: Use provided configuration
  include_vars:
    file: "{{ test_configuration }}"
  when: test_configuration is defined

- name: Checkout kickstart tests repo
  become_user: "{{ kstest_remote_user }}"
  git:
    repo: "{{ kstest_git_repo }}"
    dest: "/home/{{ kstest_remote_user }}/{{ kstest.master.dir.git_repo }}"
    version: "{{ kstest_git_version }}"
    update: no

- name: Install and configure script for remote run
  template:
    src: run_tests.sh.j2
    dest: /home/{{ kstest_remote_user }}/run_tests.sh
    owner: "{{ kstest_remote_user }}"
    group: "{{ kstest_remote_user }}"
    mode: 0755

- name: Create direcotry for repos override fragment
  file:
    path: /home/{{ kstest_remote_user }}/{{ fragments_override_dir }}/{{ override_repos_file_path | dirname }}
    state: directory
    owner: "{{ kstest_remote_user }}"
    group: "{{ kstest_remote_user }}"
    mode: 0755

- name: Create repositories override fragment
  template:
    src: override_repos_default.ks.j2
    dest: /home/{{ kstest_remote_user }}/{{ fragments_override_dir }}/{{ override_repos_file_path }}
    owner: "{{ kstest_remote_user }}"
    group: "{{ kstest_remote_user }}"
    mode: 0755

- name: Install script for creating tests history summary
  copy:
    src: "{{ kstest.master.results_summary_script.src }}"
    dest: "/home/kstest/{{ kstest.master.results_summary_script.dest }}"
    owner: "{{ kstest_remote_user }}"
    group: "{{ kstest_remote_user }}"
    mode: 0755
  when: kstest.master.results_summary_script.src is defined
