---

- hosts: localhost
  become: false

  tasks:
  - name: Delete OpenStack public key
    os_keypair:
      cloud: "{{ cloud_profile }}"
      state: absent
      name: "{{ key_name }}"
    when:
      key_mode == "delete"

  - name: Generate or use OpenStack public key
    block:
      - os_keypair:
          cloud: "{{ cloud_profile }}"
          state: present
          name: "{{ key_name }}"
        register: result
      - set_fact:
          public_key: "{{ result.key.public_key | default('') }}"
          private_key: "{{ result.key.private_key | default('') }}"
    when:
      key_mode  == "generate" or key_mode == "existing"

  - name: Upload a key to OpenStack
    block:
      - os_keypair:
          cloud: "{{ cloud_profile }}"
          state: present
          name: "{{ key_name }}"
          public_key_file: "{{ upload_key_file }}"
        register: result
      - set_fact:
          public_key: "{{ result.key.public_key | default('') }}"
          private_key: "{{ result.key.private_key | default('') }}"
    when:
      key_mode  == "upload"

  - name: Drop private key into provided path
    copy:
      content: "{{ private_key }}"
      dest: "{{ store_private_key_path }}"
      mode: 0600
    when: store_private_key_path is defined and store_private_key_path != "" and private_key != ""

  - name: Drop public key into provided path
    copy:
      content: "{{ public_key }}"
      dest: "{{ store_public_key_path }}"
      mode: 0644
    when: store_public_key_path is defined and store_public_key_path != "" and public_key != ""
