---

- hosts: localhost
  become: false

  tasks:
  - name: Wait for provisioned hosts' ssh service
    wait_for:
      host: "{{ item }}"
      port: 22
      delay: 1
      timeout: "{{ timeout }}"
    with_items: "{{ groups['all'] }}"
