---
- hosts:
    kstest-controller
  become: true
  become_user: root

  gather_facts: False
  pre_tasks:
    - name: Install python2 for Ansible
      raw: rpm -q python2 > /dev/null || dnf -y install python2
      register: output
      changed_when: output.stdout != ""
      when: ansible_python_interpreter is not defined
    - name: Gathering facts
      setup:

  roles:
    - kstest-controller
