# Dummy workflow to allow workflow_dispatch on a branch
name: Dummy workflow to allow workflow_dispatch on a branch
on:
  workflow_dispatch:

jobs:
  echo-me:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I am running on a branch".
