# Run only a few tests for x1.large
name: Test run of only few tests
on:
  # be able to start this action manually from a actions tab when needed
  workflow_dispatch:
    ref: rtt-pipeline

jobs:
  scenario:
    name: Scenario
    runs-on: [self-hosted, kstest-rtt-pipeline]
    strategy:
      matrix:
        scenario: [rtt-pipeline-test]
      fail-fast: false

    # these settings depend on the infrastructure;
    timeout-minutes: 60
    env:
      TEST_JOBS: 4
      GITHUB_TOKEN: /home/github/github-token

    steps:
      # self-hosted runners don't do this automatically; also useful to keep stuff around for debugging
      # need to run sudo as the launch script and the container create root/other user owned files
      - name: Clean up previous run
        run: |
          sudo podman ps -q --all --filter='ancestor=kstest-runner' | xargs -tr sudo podman rm -f
          sudo podman volume rm --all || true
          sudo rm -rf *

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          ref: rtt-pipeline

      # use the latest official packages for the nightly runs
      - name: Clean up squid cache
        run: sudo containers/squid.sh clean

      - name: Ensure http proxy is running
        run: sudo containers/squid.sh start

      - name: Run scenario ${{ matrix.scenario }} in container
        run: sudo --preserve-env=TEST_JOBS,GITHUB_TOKEN containers/runner/scenario ${{ matrix.scenario }} --defaults .github/defaults.sh

      - name: Collect logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: 'logs-${{ matrix.scenario }}'
          # skip the /anaconda subdirectories, too large
          path: |
            data/logs/kstest.log
            data/logs/kstest-*/*.log
            data/logs/kstest-*/anaconda/lorax-packages.log
